In [188]:
# 파이썬 정형 데이터 전처리 라이브러리 pandas 추가
import pandas as pd

# 데이터프레임 df에 '../da_data/gapminder.tsv' 있는 파일 탭('\t')으로 구분하며 열기
# csv = comma seperated value
# tsv = tap seperated value
# tsv를 열고 싶으면 read_csv() 함수의 sep 속성으로 탭 지정해주기

df = pd.read_csv('../da_data/gapminder.tsv', sep='\t')
# print(df.head())

df

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [189]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [190]:
print(type(df))
print(df.shape)

<class 'pandas.DataFrame'>
(1704, 6)

In [191]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   str
 1   continent  1704 non-null   str
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 80.0 KB

In [192]:
country_col = df['country']
print(country_col)

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: str

In [193]:
subset = df[['country', 'continent', 'year']]
print(type(subset))

<class 'pandas.DataFrame'>

In [194]:
df.set_index('country')

            continent  year  lifeExp       pop   gdpPercap
country
Afghanistan      Asia  1952   28.801   8425333  779.445314
Afghanistan      Asia  1957   30.332   9240934  820.853030
Afghanistan      Asia  1962   31.997  10267083  853.100710
Afghanistan      Asia  1967   34.020  11537966  836.197138
Afghanistan      Asia  1972   36.088  13079460  739.981106
...               ...   ...      ...       ...         ...
Zimbabwe       Africa  1987   62.351   9216418  706.157306
Zimbabwe       Africa  1992   60.377  10704340  693.420786
Zimbabwe       Africa  1997   46.809  11404948  792.449960
Zimbabwe       Africa  2002   39.989  11926563  672.038623
Zimbabwe       Africa  2007   43.487  12311143  469.709298

[1704 rows x 5 columns]

In [195]:
df.loc[0]
df.loc[0:3]

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138

In [196]:
df.iloc[0]
df.iloc[0:3]

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710

In [197]:
df.iloc[-1]

country        Zimbabwe
continent        Africa
year               2007
lifeExp          43.487
pop            12311143
gdpPercap    469.709298
Name: 1703, dtype: object

In [198]:
df.iloc[[0]]

       country continent  year  lifeExp      pop   gdpPercap
0  Afghanistan      Asia  1952   28.801  8425333  779.445314

In [199]:
# 가장 왼쪽 값 (인덱스)
df.loc[0, 'continent']

'Asia'

In [200]:
df.iloc[0, 1]

'Asia'

In [201]:
df.iloc[0:5, [1,5]]

  continent   gdpPercap
0      Asia  779.445314
1      Asia  820.853030
2      Asia  853.100710
3      Asia  836.197138
4      Asia  739.981106

In [202]:
pd.Series()

Series([], dtype: object)

In [203]:
pd.Series(['WesMcKinney', 'CreatorofPandas'])

0        WesMcKinney
1    CreatorofPandas
dtype: str

In [204]:
pd.Series(['WesMcKinney', 'CreatorofPandas'], index=['Person', 'Who'])

Person        WesMcKinney
Who       CreatorofPandas
dtype: str

In [205]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [206]:
scientists = pd.DataFrame({
'Name':['Rosaline Franklin','William Gosset'],
'Occupation':['Chemist','Statistician'],
'Born':['1920-07-25','1876-06-13'],
'Died':['1958-04-16','1937-10-16'],
'Age':[37,61]})
scientists

                Name    Occupation        Born        Died  Age
0  Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
1     William Gosset  Statistician  1876-06-13  1937-10-16   61

In [207]:
pd.DataFrame([[1,2,3],[4,5,6]], columns=['col1', 'col2', 'col3'])

   col1  col2  col3
0     1     2     3
1     4     5     6

In [208]:
Scientists = pd.DataFrame(
data={'Occupation':['Chemist','Statistician'],
'Born':['1920-07-25','1876-06-13'],
'Died':['1958-04-16','1937-10-16'],
'Age':[37,61]},
index=['Rosaline Franklin','William Gosset'],
columns=['Occupation','Born','Age','Died'])
Scientists

                     Occupation        Born  Age        Died
Rosaline Franklin       Chemist  1920-07-25   37  1958-04-16
William Gosset     Statistician  1876-06-13   61  1937-10-16

In [209]:
person = pd.DataFrame(columns = ['이름', '나이', '폰'])
person

Empty DataFrame
Columns: [이름, 나이, 폰]
Index: []

In [210]:
person

Empty DataFrame
Columns: [이름, 나이, 폰]
Index: []

In [211]:
# len() 함수는 데이터프레임에서는 행의 개수를 리턴함.
person.loc[len(person)] = ['김', '50', '010-1234-5678']
person

  이름  나이              폰
0  김  50  010-1234-5678

In [212]:
df.values

array([['Afghanistan', 'Asia', 1952, 28.801, 8425333, 779.4453145],
       ['Afghanistan', 'Asia', 1957, 30.332, 9240934, 820.8530296],
       ['Afghanistan', 'Asia', 1962, 31.997, 10267083, 853.10071],
       ...,
       ['Zimbabwe', 'Africa', 1997, 46.809, 11404948, 792.4499603],
       ['Zimbabwe', 'Africa', 2002, 39.989, 11926563, 672.0386227],
       ['Zimbabwe', 'Africa', 2007, 43.487, 12311143, 469.7092981]],
      shape=(1704, 6), dtype=object)

In [213]:
scientists = pd.read_csv('../da_data/scientists.csv')
ages = scientists['Age']
ages

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [214]:
scientists.isin([37, 41, 45])

    Name   Born   Died    Age  Occupation
0  False  False  False   True       False
1  False  False  False  False       False
2  False  False  False  False       False
3  False  False  False  False       False
4  False  False  False  False       False
5  False  False  False   True       False
6  False  False  False   True       False
7  False  False  False  False       False

In [215]:
scientists.isnull()

    Name   Born   Died    Age  Occupation
0  False  False  False  False       False
1  False  False  False  False       False
2  False  False  False  False       False
3  False  False  False  False       False
4  False  False  False  False       False
5  False  False  False  False       False
6  False  False  False  False       False
7  False  False  False  False       False

In [216]:
scientists.isin([37, 41, 45]).sum()

Name          0
Born          0
Died          0
Age           3
Occupation    0
dtype: int64

In [217]:
scientists.count()
scientists.info

<bound method DataFrame.info of                    Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician>

In [218]:
df['continent'].value_counts()

continent
Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: count, dtype: int64

In [219]:
df['year'].unique()

array([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
       2007])

In [220]:
ages.dtype

dtype('int64')

In [221]:
scientists.replace(37, 40)

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   40             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [222]:
scientists.loc[0, 'Age'] = 40
scientists

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   40             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [223]:
scientists.describe()

             Age
count   8.000000
mean   59.500000
std    17.832555
min    40.000000
25%    44.000000
50%    58.500000
75%    68.750000
max    90.000000

In [224]:
# 0.1 = 10%
scientists.sample(frac=0.1)

           Name        Born        Died  Age     Occupation
7  Johann Gauss  1777-04-30  1855-02-23   77  Mathematician

In [225]:
random = scientists.sample()
random.iloc[0]

Name          Marie Curie
Born           1867-11-07
Died           1934-07-04
Age                    66
Occupation        Chemist
Name: 3, dtype: object

In [226]:
df.sample(5).sort_index(ascending=True)

        country continent  year  lifeExp       pop     gdpPercap
125       Benin    Africa  1977   49.190   3168267   1029.161251
566     Germany    Europe  1962   70.300  73739117  12902.462910
976   Mauritius    Africa  1972   62.944    851334   2575.484158
1490      Syria      Asia  1962   50.305   4834621   2193.037133
1585     Uganda    Africa  1957   42.571   6675501    774.371069

In [227]:
df.sort_values('country', ascending=True)

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
11    Afghanistan      Asia  2007   43.828  31889923  974.580338
10    Afghanistan      Asia  2002   42.129  25268405  726.734055
9     Afghanistan      Asia  1997   41.763  22227415  635.341351
7     Afghanistan      Asia  1987   40.822  13867957  852.395945
...           ...       ...   ...      ...       ...         ...
1693     Zimbabwe    Africa  1957   50.469   3646340  518.764268
1692     Zimbabwe    Africa  1952   48.451   3080907  406.884115
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1696     Zimbabwe    Africa  1972   55.635   5861135  799.362176
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [228]:
ages.to_frame()

   Age
0   37
1   61
2   90
3   66
4   56
5   45
6   41
7   77

In [229]:
a = [1, 2, 3] + [4, 5, 6]
print(a)

[1, 2, 3, 4, 5, 6]

In [230]:
print(ages)

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [231]:
AGE = ages + ages

print(AGE)

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

In [232]:
ages + 10

0     47
1     71
2    100
3     76
4     66
5     55
6     51
7     87
Name: Age, dtype: int64

In [233]:
ages + pd.Series([1, 100])

0     38.0
1    161.0
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
dtype: float64

In [234]:
ages + pd.Series([100, 100, 3, 1])

0    137.0
1    161.0
2     93.0
3     67.0
4      NaN
5      NaN
6      NaN
7      NaN
dtype: float64

In [235]:
rev_ages = ages.sort_index(ascending=False)
print(rev_ages)

7    77
6    41
5    45
4    56
3    66
2    90
1    61
0    37
Name: Age, dtype: int64

In [236]:
AGES2 = ages + rev_ages
print(AGES2)

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

In [237]:
ages
scientists['Age']

# 한 시리즈 전체 값의 평균 리턴
scientists['Age'].mean()

np.float64(59.5)

In [238]:
# Age의 각 나이가 scientists 데이터프레임의 평균 Age보다 
# 높으면 True, 낮으면 False리턴
scientists['Age'] > scientists['Age'].mean()

0    False
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: Age, dtype: bool

In [239]:
scientists[scientists['Age'] > scientists['Age'].mean()]

                   Name        Born        Died  Age     Occupation
1        William Gosset  1876-06-13  1937-10-16   61   Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90          Nurse
3           Marie Curie  1867-11-07  1934-07-04   66        Chemist
7          Johann Gauss  1777-04-30  1855-02-23   77  Mathematician

In [240]:
print(scientists['Age'].mean())

59.5

In [241]:
# df에서 df의 나라가 한국인 행 찾기
df[df['country'] == 'Korea, Rep.']

         country continent  year  lifeExp       pop     gdpPercap
840  Korea, Rep.      Asia  1952   47.453  20947571   1030.592226
841  Korea, Rep.      Asia  1957   52.681  22611552   1487.593537
842  Korea, Rep.      Asia  1962   55.292  26420307   1536.344387
843  Korea, Rep.      Asia  1967   57.716  30131000   2029.228142
844  Korea, Rep.      Asia  1972   62.612  33505000   3030.876650
845  Korea, Rep.      Asia  1977   64.766  36436000   4657.221020
846  Korea, Rep.      Asia  1982   67.123  39326000   5622.942464
847  Korea, Rep.      Asia  1987   69.810  41622000   8533.088805
848  Korea, Rep.      Asia  1992   72.244  43805450  12104.278720
849  Korea, Rep.      Asia  1997   74.647  46173816  15993.527960
850  Korea, Rep.      Asia  2002   77.045  47969150  19233.988180
851  Korea, Rep.      Asia  2007   78.623  49044790  23348.139730

In [242]:
scientists[[True, False, True, False, True, False, True, False]]

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   40             Chemist
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist

In [243]:
print(scientists['Born'].dtype)

str

In [244]:
# Born의 데이터 타입을 str에서 datetime64[ns]로 변경
scientists['Born'].astype('datetime64[ns]')

0   1920-07-25
1   1876-06-13
2   1820-05-12
3   1867-11-07
4   1907-05-27
5   1813-03-15
6   1912-06-23
7   1777-04-30
Name: Born, dtype: datetime64[ns]

In [245]:
# 기존 데이터프레임을 변경시키는 것이 아니므로 
# dtype 출력시 그대로 출력됨.
print(scientists['Born'].dtype)

str

In [246]:
# 데이터 타입을 변경하여 원본 데이터에 반영
scientists['Born'] = scientists['Born'].astype('datetime64[ns]')

In [247]:
# 원본에 반영됨.
print(scientists['Born'].dtype)

datetime64[ns]

In [248]:
print(scientists['Born'].dt.year)
print(scientists['Born'].dt.month)
print(scientists['Born'].dt.day)
print(scientists['Born'].dt.quarter)

0    1920
1    1876
2    1820
3    1867
4    1907
5    1813
6    1912
7    1777
Name: Born, dtype: int32
0     7
1     6
2     5
3    11
4     5
5     3
6     6
7     4
Name: Born, dtype: int32
0    25
1    13
2    12
3     7
4    27
5    15
6    23
7    30
Name: Born, dtype: int32
0    3
1    2
2    2
3    4
4    2
5    1
6    2
7    2
Name: Born, dtype: int32

In [249]:
born_datetime = pd.to_datetime(scientists['Born'], format='%Y-%m-%d')
died_datetime = pd.to_datetime(scientists['Died'], format='%Y-%m-%d') 

scientists['born_dt'], scientists['died_dt']=(born_datetime, died_datetime)
scientists.head()

,Name,Born,Died,Age,Occupation,born_dt,died_dt
0,Rosaline Franklin,1920-07-25,1958-04-16,40,Chemist,1920-07-25,1958-04-16
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,1876-06-13,1937-10-16
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,1820-05-12,1910-08-13
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,1867-11-07,1934-07-04
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,1907-05-27,1964-04-14

In [250]:
# axis : 축
# axis=0 : 세로 (인덱스를 의미)
# axis=1 : 가로 (컬럼을 의미)

# test라는 컬럼 삭제
scientists.drop(['born_dt', 'died_dt'], axis=1)

                   Name       Born        Died  Age          Occupation
0     Rosaline Franklin 1920-07-25  1958-04-16   40             Chemist
1        William Gosset 1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale 1820-05-12  1910-08-13   90               Nurse
3           Marie Curie 1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson 1907-05-27  1964-04-14   56           Biologist
5             John Snow 1813-03-15  1858-06-16   45           Physician
6           Alan Turing 1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss 1777-04-30  1855-02-23   77       Mathematician

In [251]:
# pd.read_csv

# index = False 지정하여 index를 저장하지 않기.
scientists.to_csv('../da_data/scientists_df.csv', index = False)

In [252]:
import pandas as pd

# 특정 컬럼을 인덱스로 지정하여 불러오기
pd.read_csv('../da_data/scientists_df.csv', index_col='Name')

#

,Born,Died,Age,Occupation,born_dt,died_dt
Name,,,,,,
Rosaline Franklin,1920-07-25,1958-04-16,40,Chemist,1920-07-25,1958-04-16
William Gosset,1876-06-13,1937-10-16,61,Statistician,1876-06-13,1937-10-16
Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,1820-05-12,1910-08-13
Marie Curie,1867-11-07,1934-07-04,66,Chemist,1867-11-07,1934-07-04
Rachel Carson,1907-05-27,1964-04-14,56,Biologist,1907-05-27,1964-04-14
John Snow,1813-03-15,1858-06-16,45,Physician,1813-03-15,1858-06-16
Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,1912-06-23,1954-06-07
Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,1777-04-30,1855-02-23

In [ ]:
# 이 방식 사용 시, DB에서 데이터를 불러올 수는 있는데
# 저장이 불가능함.
import pymysql
import pandas as pd

conn = pymysql.connect(host="121.152.203.186", user="test",
password="1234", port=33060,
database="python_db")

users = pd.read_sql('select * from users', conn)
orders = pd.read_sql('select * from orders', conn)
conn.close()

In [264]:
# 데이터베이스 서버에 더 쉽게 접속하기 위한 라이브러리
# connect(), cursor, cursor.close(), 
# connect.close()를 하지 않아도 됨.
import sqlalchemy as sqlal
import pandas as pd

engine = sqlal.create_engine('mysql+pymysql://test:1234@121.152.203.186:33060/python_db')

emp = pd.read_sql('select * from emp', engine)
joined_emp = pd.read_sql('select * from emp join dept on emp.deptno = dept.deptno', engine)
print(joined_emp)

    empno   ename        job     mgr    hiredate     sal    comm  deptno  \
0    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
2    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
3    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
7    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
8    7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
9    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
11   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
12   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
13   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

    deptno       dname       loc
0       20    RESEARCH    DALLAS
1       30       SALES   CHICAGO
2       30       SALES   CHICAGO
3       20    RESEARCH    DALLAS
4       30       SALES   CHICAGO
5       30       SALES   CHICAGO
6       10  ACCOUNTING  NEW YORK
7       20    RESEARCH    DALLAS
8       10  ACCOUNTING  NEW YORK
9       30       SALES   CHICAGO
10      20    RESEARCH    DALLAS
11      30       SALES   CHICAGO
12      20    RESEARCH    DALLAS
13      10  ACCOUNTING  NEW YORK

In [ ]:
# engine에 데이터베이스의 경로를 설정해두었으므로
# 'joined' 테이블을 engine 경로에 저장
# 만약 'joined_its_me' 테이블이 존재하면 대체
# 'joined' : 테이블 이름으로
# engine : engine에 설정한 경로로
# if_exists='append' : 만약 테이블이 존재한다면, 뒤에 이어 붙이기
# index=False : 앞에 붙은 0,1,2,3,4,... 등의 인덱스를 저장하지 않음.
emp.to_sql('', engine, if_exists='append', index=False)

14

In [262]:
emp.dtypes

empno         int64
ename           str
job             str
mgr         float64
hiredate     object
sal         float64
comm        float64
deptno        int64
dtype: object

In [265]:
import pandas as pd

df1 = pd.read_csv('../da_data/concat_1.csv')
df2 = pd.read_csv('../da_data/concat_2.csv')
df3 = pd.read_csv('../da_data/concat_3.csv')

In [266]:
row_concat = pd.concat([df1, df2, df3])
row_concat

     A    B    C    D
0   a0   b0   c0   d0
1   a1   b1   c1   d1
2   a2   b2   c2   d2
3   a3   b3   c3   d3
0   a4   b4   c4   d4
1   a5   b5   c5   d5
2   a6   b6   c6   d6
3   a7   b7   c7   d7
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [268]:
row_concat.loc[3]

     A    B    C    D
3   a3   b3   c3   d3
3   a7   b7   c7   d7
3  a11  b11  c11  d11

In [269]:
pd.concat([df1, df2, df3], ignore_index = True)

      A    B    C    D
0    a0   b0   c0   d0
1    a1   b1   c1   d1
2    a2   b2   c2   d2
3    a3   b3   c3   d3
4    a4   b4   c4   d4
5    a5   b5   c5   d5
6    a6   b6   c6   d6
7    a7   b7   c7   d7
8    a8   b8   c8   d8
9    a9   b9   c9   d9
10  a10  b10  c10  d10
11  a11  b11  c11  d11

In [271]:
# 컬럼 이름 변경 가능
df1.columns = ['A', 'B', 'C', 'D']
df2.columns = ['E', 'F', 'G', 'H']
df3.columns = ['A', 'C', 'F', 'H']

In [273]:
# 두 데이터프레임의 컬럼이 일치하지 않으면
# sql의 outer join처럼 동작함.

pd.concat([df1, df3])

     A    B    C    D    F    H
0   a0   b0   c0   d0  NaN  NaN
1   a1   b1   c1   d1  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN
3   a3   b3   c3   d3  NaN  NaN
0   a8  NaN   b8  NaN   c8   d8
1   a9  NaN   b9  NaN   c9   d9
2  a10  NaN  b10  NaN  c10  d10
3  a11  NaN  b11  NaN  c11  d11

In [274]:
# df3의 열들을 df1의 열으로 덮어씌워 같게 만듬.
df3.columns = df1.columns

pd.concat([df1, df3])

     A    B    C    D
0   a0   b0   c0   d0
1   a1   b1   c1   d1
2   a2   b2   c2   d2
3   a3   b3   c3   d3
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [275]:
person = pd.read_csv('../da_data/survey_person.csv')
site = pd.read_csv('../da_data/survey_site.csv')
visited = pd.read_csv('../da_data/survey_visited.csv')
survey = pd.read_csv('../da_data/survey_survey.csv')

In [279]:
# .merge() 메소드를 사용하여 데이터 연결하기
# sql로 치면 조인과 같은 개념

# == select * from site join visited on site.name = visited.name
# site와 visited를 merge (왼쪽에 name, 오른쪽에 site, 방법은 inner join)
site.merge(visited, left_on='name', right_on='site', how='inner')

    name    lat    long  ident   site       dated
0   DR-1 -49.85 -128.57    619   DR-1  1927-02-08
1   DR-1 -49.85 -128.57    622   DR-1  1927-02-10
2   DR-1 -49.85 -128.57    844   DR-1  1932-03-22
3   DR-3 -47.15 -126.72    734   DR-3  1939-01-07
4   DR-3 -47.15 -126.72    735   DR-3  1930-01-12
5   DR-3 -47.15 -126.72    751   DR-3  1930-02-26
6   DR-3 -47.15 -126.72    752   DR-3         NaN
7  MSK-4 -48.87 -123.40    837  MSK-4  1932-01-14

In [283]:
sp = survey.merge(person, left_on='person', right_on='ident')
spv = sp.merge(visited, left_on = 'taken', right_on='ident')
spvs = spv.merge(site, left_on = 'site', right_on='name')
spvs.drop(['ident_x', 'ident_y', 'name'], axis=1)

,taken,person,quant,reading,personal,family,site,dated,lat,long
0,619,dyer,rad,9.82,William,Dyer,DR-1,1927-02-08,-49.85,-128.57
1,619,dyer,sal,0.13,William,Dyer,DR-1,1927-02-08,-49.85,-128.57
2,622,dyer,rad,7.80,William,Dyer,DR-1,1927-02-10,-49.85,-128.57
3,622,dyer,sal,0.09,William,Dyer,DR-1,1927-02-10,-49.85,-128.57
4,734,pb,rad,8.41,Frank,Pabodie,DR-3,1939-01-07,-47.15,-126.72
5,734,lake,sal,0.05,Anderson,Lake,DR-3,1939-01-07,-47.15,-126.72
6,734,pb,temp,-21.50,Frank,Pabodie,DR-3,1939-01-07,-47.15,-126.72
7,735,pb,rad,7.22,Frank,Pabodie,DR-3,1930-01-12,-47.15,-126.72
8,751,pb,rad,4.35,Frank,Pabodie,DR-3,1930-02-26,-47.15,-126.72
9,751,pb,temp,-18.50,Frank,Pabodie,DR-3,1930-02-26,-47.15,-126.72
10,751,lake,sal,0.10,Anderson,Lake,DR-3,1930-02-26,-47.15,-126.72
11,752,lake,rad,2.19,Anderson,Lake,DR-3,NaN,-47.15,-126.72
12,752,lake,sal,0.09,Anderson,Lake,DR-3,NaN,-47.15,-126.72
13,752,lake,temp,-16.00,Anderson,Lake,DR-3,NaN,-47.15,-126.72
14,752,roe,sal,41.60,Valentina,Roerich,DR-3,NaN,-47.15,-126.72
15,837,lake,rad,1.46,Anderson,Lake,MSK-4,1932-01-14,-48.87,-123.40
16,837,lake,sal,0.21,Anderson,Lake,MSK-4,1932-01-14,-48.87,-123.40
17,837,roe,sal,22.50,Valentina,Roerich,MSK-4,1932-01-14,-48.87,-123.40
18,844,roe,rad,11.25,Valentina,Roerich,DR-1,1932-03-22,-49.85,-128.57

In [294]:
import numpy as np

In [295]:
# emp의 mgr속성에서 null인 행들만 리턴
emp[emp['mgr'].isnull()]

   empno ename        job  mgr    hiredate     sal  comm  deptno
8   7839  KING  PRESIDENT  NaN  1981-11-17  5000.0   NaN      10

In [ ]:
# comm 컬럼이 null인 행들만 출력
emp[emp['comm'].isnull()]

    empno   ename        job     mgr    hiredate     sal  comm  deptno
0    7369   SMITH      CLERK  7902.0  1980-12-17   800.0   NaN      20
3    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0   NaN      20
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0   NaN      30
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0   NaN      10
7    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000.0   NaN      20
8    7839    KING  PRESIDENT     NaN  1981-11-17  5000.0   NaN      10
10   7876   ADAMS      CLERK  7788.0  1987-05-23  1100.0   NaN      20
11   7900   JAMES      CLERK  7698.0  1981-12-03   950.0   NaN      30
12   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0   NaN      20
13   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0   NaN      10

In [302]:
# comm 컬럼이 null이 아닌 행들만 리턴
emp[emp['comm'].notnull()]

   empno   ename       job     mgr    hiredate     sal    comm  deptno
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
2   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
4   7654  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
9   7844  TURNER  SALESMAN  7698.0  1981-09-08  1500.0     0.0      30

In [314]:
import pandas as pd
ebola = pd.read_csv('../da_data/country_timeseries.csv')
ebola.head()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN

In [315]:
ebola.interpolate()

TypeError: Cannot interpolate with str dtype

In [310]:
ebola.bfill()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,8166.0,10030.0,20.0,1.0,4.0,1.0,7.0,1786.0,3496.0,2977.0,8.0,0.0,1.0,0.0,6.0
1,1/4/2015,288,2775.0,8166.0,9780.0,20.0,1.0,4.0,1.0,7.0,1781.0,3496.0,2943.0,8.0,0.0,1.0,0.0,6.0
2,1/3/2015,287,2769.0,8166.0,9722.0,20.0,1.0,4.0,1.0,7.0,1767.0,3496.0,2915.0,8.0,0.0,1.0,0.0,6.0
3,1/2/2015,286,2730.0,8157.0,9633.0,20.0,1.0,4.0,1.0,7.0,1739.0,3496.0,2827.0,8.0,0.0,1.0,0.0,6.0
4,12/31/2014,284,2730.0,8115.0,9633.0,20.0,1.0,4.0,1.0,7.0,1739.0,3471.0,2827.0,8.0,0.0,1.0,0.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,3/27/2014,5,103.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,66.0,6.0,5.0,NaN,NaN,NaN,NaN,NaN
118,3/26/2014,4,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,3/25/2014,3,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,3/24/2014,2,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,3/22/2014,0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [309]:
ebola.ffill()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,2769.0,8157.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,3/27/2014,5,103.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,66.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
118,3/26/2014,4,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,62.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
119,3/25/2014,3,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,60.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
120,3/24/2014,2,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,59.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
121,3/22/2014,0,49.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,29.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0

In [ ]:
# fillna() : fill not available
ebola.fillna(0)

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,0.0,10030.0,0.0,0.0,0.0,0.0,0.0,1786.0,0.0,2977.0,0.0,0.0,0.0,0.0,0.0
1,1/4/2015,288,2775.0,0.0,9780.0,0.0,0.0,0.0,0.0,0.0,1781.0,0.0,2943.0,0.0,0.0,0.0,0.0,0.0
2,1/3/2015,287,2769.0,8166.0,9722.0,0.0,0.0,0.0,0.0,0.0,1767.0,3496.0,2915.0,0.0,0.0,0.0,0.0,0.0
3,1/2/2015,286,0.0,8157.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3496.0,0.0,0.0,0.0,0.0,0.0,0.0
4,12/31/2014,284,2730.0,8115.0,9633.0,0.0,0.0,0.0,0.0,0.0,1739.0,3471.0,2827.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,3/27/2014,5,103.0,8.0,6.0,0.0,0.0,0.0,0.0,0.0,66.0,6.0,5.0,0.0,0.0,0.0,0.0,0.0
118,3/26/2014,4,86.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119,3/25/2014,3,86.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
120,3/24/2014,2,86.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
121,3/22/2014,0,49.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0